name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/pachof/android_kernel_huawei_franklin
          kernel-branch: main
â€Ž
          arch: arm64
          other-gcc64-url: https://github.com/KudProject/aarch64-linux-android-4.9
          other-gcc64-branch: master
          other-gcc32-url: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9
          other-gcc32-branch: lineage-17.1
          android-version: 10
          extra-make-args: olddefconfig
